name: Build/Publish Docker Images and, optionally, Singularity Images on CVMFS

inputs:
  github_token:
    description: |
      a PAT so the action can git push to github (images and cvmfs requests)
    required: true
  image:
    description: |
      the full-qualified image (tagless) --
        include a registry if not storing with dockerhub
        ex: 'ghcr.io/foo/bar', 'foo/bar', etc.
    required: true
  action:
    description: |
      what action to perform
        BUILD                   - build and publish 'inputs.image'
        CVMFS_BUILD             - BUILD, then request CVMFS to build and persist 'inputs.image'
        CVMFS_REMOVE            - request CVMFS to delete 'inputs.cvmfs_remove_images'
        CVMFS_REMOVE_THEN_BUILD - CVMFS_REMOVE, then CVMFS_BUILD
    required: true
  # OPTIONAL
  cvmfs_dest_dir:
    description: |
      IF USING CVMFS (else, var is ignored):
        the CVMFS directory to place the singularity image built from the docker image
    default: ""
    required: false
  free_disk_space:
    description: |
      IF BUILDING VERY LARGE IMAGES (else, var is ignored):
        whether to free disk space on the GitHub runner before building the image
    default: false
    type: boolean
    required: false
  build_platform:
    description: |
      IF BUILDING IMAGE (else, var is ignored):
        what CPU architecture platform to use when building the image
    default: "linux/amd64"
    required: false


runs:
  using: "composite"

  steps:

    ####################################################################################
    # Prep before action logic
    ####################################################################################

    - name: Validate and Prep Image Tag Variables
      if: always()
      run: |
        # step: Validate and Prep Image Tag Variables
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        # validate slash-format
        if [[ ! "${{ inputs.image }}" =~ ^[^/]+/[^/]+(/[^/]+)?$ ]]; then
            echo "::error::'inputs.image' (${{ inputs.image }}) must be in the form 'NAMESPACE/IMAGE' or 'REGISTRY/NAMESPACE/IMAGE'"
            exit 1
        fi
        
        # validate there's no tag or digest attached
        last_segment=$(basename "${{ inputs.image }}")
        if [[ "$last_segment" == *:* || "$last_segment" == *@* ]]; then
            echo "::error::'inputs.image' (${{ inputs.image }}) must not include a tag or digest"
            exit 1
        else
            echo "IMAGE_NAME=$last_segment" >> "$GITHUB_ENV"
        fi
      shell: bash

    - name: Action determination logic (set defaults)
      if: always()
      run: |
        # step: Action determination logic (set defaults)
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        echo "DO_2_BUILD=false" >> "$GITHUB_ENV"
        echo "DO_3_CVMFS_BUILD=false" >> "$GITHUB_ENV"
        echo "DO_1_CVMFS_REMOVE=false" >> "$GITHUB_ENV"
      shell: bash

    - name: Action determination logic - DO_2_BUILD
      if: |
        inputs.action == 'BUILD' || 
        inputs.action == 'CVMFS_BUILD' || 
        inputs.action == 'CVMFS_REMOVE_THEN_BUILD'
      run: echo "DO_2_BUILD=true" >> "$GITHUB_ENV"
      shell: bash

    - name: Action determination logic - DO_3_CVMFS_BUILD
      if: |
        inputs.action == 'CVMFS_BUILD' || 
        inputs.action == 'CVMFS_REMOVE_THEN_BUILD'
      run: echo "DO_3_CVMFS_BUILD=true" >> "$GITHUB_ENV"
      shell: bash

    - name: Action determination logic - DO_1_CVMFS_REMOVE
      if: |
        inputs.action == 'CVMFS_REMOVE' || 
        inputs.action == 'CVMFS_REMOVE_THEN_BUILD'
      run: echo "DO_1_CVMFS_REMOVE=true" >> "$GITHUB_ENV"
      shell: bash

    - name: Summary (appears in GitHub UI)
      if: always()
      run: |
        # step: Summary (appears in GitHub UI)
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"

        {
          echo "# ðŸš€ Workflow Plan"
          echo ""
          echo "### ðŸ”§ Inputs"
          echo "- \`image\`: ${{ inputs.image }}"
          echo "- \`action\`: ${{ inputs.action }}"
          echo "- \`platform\`: ${{ inputs.build_platform }}"
          echo "- \`free_disk_space\`: ${{ inputs.free_disk_space }}"
          echo "- \`cvmfs_dest_dir\`: ${{ inputs.cvmfs_dest_dir }}"
          echo ""
          echo "### ðŸ“‹ Interpreted Configuration"
          echo "- \`image_name\`: ${{ env.IMAGE_NAME }}"
          echo ""
          echo "### â­ï¸ Planned Steps"
          [[ "${{ env.DO_1_CVMFS_REMOVE }}" == 'true' ]] && echo "- Will request CVMFS image removal"
          [[ "${{ env.DO_2_BUILD }}" == 'true' ]] && echo "- Will build & push Docker image" || echo "- Will skip Docker build"
          [[ "${{ env.DO_3_CVMFS_BUILD }}" == 'true' ]] && echo "- Will request CVMFS Singularity image build"
          echo ""
          echo "_Summary generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")_"
        } >> "$GITHUB_STEP_SUMMARY"
      shell: bash


    ####################################################################################
    # Do: Remove CVMFS
    ####################################################################################

    - if: env.DO_1_CVMFS_REMOVE == 'true'
      name: Request Removing Image(s) from CVMFS
      uses: WIPACrepo/build-singularity-cvmfs-action@v2.0
      with:
        github_token: ${{ inputs.github_token }}  # so job can git push
        delete_image_tags: "${{ env.IMAGE_NAME }}:${{ github.ref_name }}-[SHA]"
        dest_dir: ${{ inputs.cvmfs_dest_dir }}  # Required for constructing path pattern


    ####################################################################################
    # Do: Build + Publish Docker Image
    ####################################################################################

    - if: env.DO_2_BUILD == 'true' && inputs.free_disk_space == 'true'
      uses: jlumbroso/free-disk-space@main  # clears space for image build
      with:
        docker-images: false  # keep docker otherwise build will re-download them

    - if: env.DO_2_BUILD == 'true'
      uses: actions/checkout@v4
      with:
        ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)

    - if: env.DO_2_BUILD == 'true'
      id: docker_meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ inputs.image }}
        tags: |
          # branches (PRs)
          type=sha,prefix={{branch}}-,enable=${{ github.ref_type == 'branch' }}
          # release tags
          type=semver,pattern={{major}},enable=${{ github.ref_type == 'tag' }}
          type=semver,pattern={{major}}.{{minor}},enable=${{ github.ref_type == 'tag' }}
          type=semver,pattern={{major}}.{{minor}}.{{patch}},enable=${{ github.ref_type == 'tag' }}

    - if: env.DO_2_BUILD == 'true' && ! startsWith(inputs.image, 'ghcr.io/')
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - if: env.DO_2_BUILD == 'true' && startsWith(inputs.image, 'ghcr.io/')
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - if: env.DO_2_BUILD == 'true' && contains(inputs.build_platform, 'arm')
      name: Setup QEMU (if platform requires it)
      uses: docker/setup-qemu-action@v2

    - if: env.DO_2_BUILD == 'true'
      uses: docker/setup-buildx-action@v2

    - if: env.DO_2_BUILD == 'true'
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: ${{ inputs.build_platform }}
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}


    ####################################################################################
    # Do: Build Image on CVMFS
    ####################################################################################

    - if: env.DO_3_CVMFS_BUILD == 'true'
      name: Request Building Singularity Image(s) on CVMFS
      uses: WIPACrepo/build-singularity-cvmfs-action@v2.0
      with:
        github_token: ${{ inputs.github_token }}  # so job can git push
        docker_tags: ${{ steps.docker_meta.outputs.tags }}
        dest_dir: ${{ inputs.cvmfs_dest_dir }}  # Required for constructing path pattern
